export const BURGER_INGREDIENTS_CONSTRUCTOR = "BURGER_INGREDIENTS_CONSTRUCTOR";
export const ADD_CONSTRUCTOR_ITEM = "ADD_CONSTRUCTOR_ITEM";
export const DELETE_CONSTRUCTOR_ITEM = "DELETE_CONSTRUCTOR_ITEM";
export const UPDATE_CONSTRUCTOR_ITEM = "UPDATE_CONSTRUCTOR_ITEM";
